Check for too big option.PipelineMultiplex value
redis/rueidis pull request #436
Opened 2023-12-28 10:36 UTC by atercattus

If we use `ClientOption.PipelineMultiplex` in the wrong way (too big), we will get a panic inside rueidis:

https://go.dev/play/p/QE8VYHE6hJX
```
package main
package main

func foo(v int) int {
	return 1 << v
}

func main() {
	println(foo(0), foo(2), foo(50), foo(70), foo(100), foo(200))
}

>> 1 4 1125899906842624 0 0 0
```

In this case we will get [zero for multiplex value](https://github.com/redis/rueidis/blob/a85dd76338d31ff6e92e55d698dd536e5ea6f10a/mux.go#L97) and zero-sized `wire`, `mu`, `sc` slices. Which will lead to panic [here](https://github.com/redis/rueidis/blob/a85dd76338d31ff6e92e55d698dd536e5ea6f10a/mux.go#L142) for example.

```
goroutine 59 [running]:
github.com/redis/rueidis.(*mux)._pipe(0x0?, 0x0?)
        /home/X/go/pkg/mod/github.com/redis/rueidis@v1.0.25/mux.go:142 +0x71e
github.com/redis/rueidis.(*mux).Dial(0x0?)
        /home/X/go/pkg/mod/github.com/redis/rueidis@v1.0.25/mux.go:188 +0x1b
github.com/redis/rueidis.(*clusterClient).init.func1({0xc00010f640, 0x19}, {0x17ce2d0, 0xc00001b180})
        /home/X/go/pkg/mod/github.com/redis/rueidis@v1.0.25/cluster.go:134 +0x48
created by github.com/redis/rueidis.(*clusterClient).init
        /home/X/go/pkg/mod/github.com/redis/rueidis@v1.0.25/cluster.go:133 +0x9d
```

2023-12-28 10:40 UTC, bald2b requested changes

2023-12-28 10:40 UTC, bald2b commented on mux.go
> +	if multiplex == 0 {
Is this good way? Because we just replace wrong value with default, but user never knows about problem.
I think better panic with explanation why

2023-12-28 11:08 UTC, rueian commented
Thanks @atercattus! And I agree with @bald2b. It will be better to return an error to users.

Actually, I don't think setting `PipelineMultiplex` to a value larger than 2 will help. The Redis documentation also suggests that ["Using more than 8 threads is unlikely to help much".](https://redis.io/docs/management/config-file/)

2023-12-28 11:40 UTC, atercattus commented
We set too big a value by mistake and got unexpected panic :)

I think, we have two ways:
- change a signature for `newMux()` to `newMux(...) (*mux, error)` and for all functions that call it
- update docs for a given behavior.

Now I'm leaning towards the second option. What do you think?

2023-12-28 11:51 UTC, rueian commented
> We set too big a value by mistake and got unexpected panic :)
> 
> I think, we have two ways:
> 
> * change a signature for `newMux()` to `newMux(...) (*mux, error)` and for all functions that call it
> * update docs for a given behavior.
> 
> Now I'm leaning towards the second option. What do you think?

I see, but changing the signature of `newMux` is too much. It requires too many changes.

I think we can just validate the value of `PipelineMultiplex` in the `NewClient`.

2023-12-28 12:03 UTC, rueian commented
We can put a hard limit of 8, resulting in 256 connections to a node.

2023-12-28 12:06 UTC, rueian approved these changes

2023-12-28 13:04 UTC, merged

2023-12-29 11:03 UTC, atercattus commented
Could you make a new tag? :)

2023-12-29 11:34 UTC, rueian commented
Sure. I will do it later.